# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Alfst.L
tagline:             'Life & Photography & Blogging'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://alfstl.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Siao-Ting Lin
  url:               https://twitter.com/mdo
  email:             linxiatin@gmail.com

# Custom vars
version:             1.0.0
